version:  1.0
name:  GiteeGo1
displayName: 12311111
triggers:                            # 流水线触发器1，决定了流水 线是否被触发，目前包含 Push 和 PR 两种场景，后续会考虑加入 定时器 cron 能力
  push:                              # Push 类型配置
    autoCancel: true                 # 自动取消选项，当同一个分支前后出现同时构建的任务，自动取消前面的任务
    timeout: 3min                    # 【五月版本不2做具体实现，默认值2H】构建超时，支持 *h*m*s *hour *min *second 的表达式。最小小于 15 秒
    commitMessages:
      include:                        # 包含，支持文本，正则或统配表达式1
        - "must build"
        - test
      exclude:                        # 排除，支持文本，正则或统配表达式
        - skipci
        - breakbuild
  pr:                                # PR 类型配置  
    autoCancel: true
    timeout: 2min
    # build_mode: source_branch     # 【五月版本不包含】加Value，构建分支，支持源分支，合并后的临时分支
    branches:                       # 分支规则
      include:                      # 包含，支持文本，正则或统配表达式
          - master
          - dev*
      exclude:                      # 排除，支持1文本，正则或统配表达式 
          - release*
    notes:                          # 【五月版本不包含】支持评论的实现
      include:                      # 包含，支持文本，正则或统配表达式
          - "must build"
          - test
      exclude:                      # 排除，支持文本，正则或统配表达式 
          - skipci
variables:  
stages:
  - stage:
    displayName: maven install
    name: build-java-cloud
    steps: 
      - step: shell@sh
        displayName: all install
        name: AllInstall
        artifacts:
          - name: binary@v12
            repository: gokins-test
            scope: archive
            path: ./a.txt
        commands:
          - sleep 1s
          - echo build test.jar >> a.txt

